### ISSUE TITLE
How to get converted model file?

### ISSUE THREAD

**Issue by TRYOKETHEPEN** [xslasd/step2glb#3]
Thanks for this project, I wonder how to get converted model file?

In "debug.js", defaultly use "LogStorage", it only print logs.
So I changed "debug.js" as follow, to get the converted model file:
```
// import { LogStorage } from "./logstorage.js";
import { ExporterWorker } from "./handler.js";
import { Storage } from './storage.js';

// const logStorage = new LogStorage()
// const exporterWorker = new ExporterWorker(logStorage)

const myCfg = {
    "callback_url": "http://127.0.0.1:1901/test1",
    "callback_file": true,
    "s3_upload_config": {
        "endPoint": "127.0.0.1",
        "port": 9010,
        "useSSL": false,
        "accessKey": "xxxx",
        "secretKey": "xxxxx",
        "bucketName": "xxx-asset"
    }
}
const myStorage = new Storage(myCfg)
const exporterWorker = new ExporterWorker(myStorage)

var data = {
    gid: "debug",
    request_id: "1",
    urlType: 2,
    url: "./testfiles/stp/test.stp",
    file_name: "test.stp",
    convert_type: "glb",
    save_path: "./",
}
exporterWorker.export(data)
```

Then I build a http server at localhost, listening to "http://127.0.0.1:1901/test1", and the method is "POST".
Then I excute "node debug.js": 

- When I set myCfg.callback_file = true :
The client result is：
```
root@AIServer:/home/projects/step2glb# node debug.js 
[debug]exportStage: FileListProgress 0,1
[debug]exportStage: FileLoadProgress 31478,31478
[debug]exportStage: ImportStart Importing model...
[debug]exportStage: ExportStart Exporting model...
[debug]executionSuccess successfully.
callback result ok.
```
The server result is:
```
{"request_id":"debug","status":"0"}
```
The problem is that **I can't find the converted model file anywhere in localhost**.

- When I set myCfg.callback_file = false:
The client result is：(**raise error**)
```
root@AIServer:/home/projects/step2glb# node debug.js 
[debug]exportStage: FileListProgress 0,1
[debug]exportStage: FileLoadProgress 31478,31478
[debug]exportStage: ImportStart Importing model...
[debug]exportStage: ExportStart Exporting model...
[debug]minioClient PutObject error: Error: connect ECONNREFUSED 127.0.0.1:9010
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9010
}
/home/projects/step2glb/node_modules/delayed-stream/lib/delayed_stream.js:33
  source.on('error', function() {});
         ^

TypeError: source.on is not a function
    at Function.DelayedStream.create (/home/projects/step2glb/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/home/projects/step2glb/node_modules/combined-stream/lib/combined_stream.js:45:37)
    at FormData.append (/home/projects/step2glb/node_modules/form-data/lib/form_data.js:75:3)
    at file:///home/projects/step2glb/storage.js:61:26
    at ObjectUploader.<anonymous> (/home/projects/step2glb/node_modules/minio/dist/main/object-uploader.js:65:7)
    at ObjectUploader.emit (node:events:377:35)
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
My nodejs & npm info is:
```
root@AIServer:/home/projects/step2glb# npm list
demo@1.0.0 /home/projects/step2glb
├── axios@1.3.4
├── draco3d@1.5.6
├── express@4.18.2
├── fflate@0.7.4
├── formidable@2.1.1
├── minio@7.0.33
├── multer@1.4.5-lts.1
├── occt-import-js@0.0.15
├── rhino3dm@7.15.0
├── three@0.150.1
└── web-ifc@0.0.39

root@AIServer:/home/projects/step2glb# node -v
v16.2.0
```

**Comment by xslasd** [comment]
const myStorage = new Storage(myCfg) and const logStorage = new LogStorage() are my implementations. You can look at the LogStorage code and implement your own corresponding methods.

**Comment by TRYOKETHEPEN** [comment]
> const myStorage = new Storage(myCfg) and const logStorage = new LogStorage() are my implementations. You can look at the LogStorage code and implement your own corresponding methods.

Thanks for reply!
I'm new to JS, it's hard to me to develop new implement. I just want to use this project to **convert model format** for now.

From a cursory analysis of the code, I get that: (maybe useful for others)

1.  The api _/convertwork/v1/importfile_ finally excute _exportWorker.export(data)_, which equals what happened in "debug.js". 
2.  The converted model, as http request form data, is generated in _Storge.executionSuccess()_ . 
3.  If _cfg.callback_file_ is set to _false_, the export use minio (I don't know its details), otherwise use axios to POST.
4.  In _data_: 
  4.1. The _gid_ & _request_id_ are just for identify.
  4.2. The _urlType_ is determined by input model's source type (file or url).
  4.3. The _url_ means input model's data path.
  4.4. The _file_name_ is always neccessary whatever urlType is. But actually it can be split from _url_ or _file_, so its a little bit confusing with these similar params (file/file_name/url).
  4.5. The _save_path_ is only used when _cfg.callback_file_ is set to _false_. 
5.  This project actually only support binary _convert_type_ such as glb, because "OV.FileFormat.Binary" is fixed in "handler.js".

Now my "debug.js" is simplified as:
```
import { ExporterWorker } from "./handler.js";
import { Storage } from './storage.js';
import { FileSource } from "./engine/main.js";

const myCfg = {
    "callback_url": "http://127.0.0.1:1901/test1", //the converted model data POST to this url
    "callback_file": true //use axios to POST
}
const myStorage = new Storage(myCfg)
const exporterWorker = new ExporterWorker(myStorage)

var data = {
    gid: "debug", // use to identify, can be random
    request_id: "1", // use to identify, can be random
    urlType: FileSource.File, //input model's source
    url: "./testfiles/stp/test.stp", //input model's data
    file_name: "test.stp", //input model's name
    convert_type: "glb", //convert type
}
exporterWorker.export(data)
```

Now my problem is:
After "node debug.js", I get _req.file=undefined_ at http server. The server is:
```
const express = require("express");
const multer = require("multer");
const cors = require("cors"); 
const app = express();
const upload = multer({ dest: "uploads/" });

app.use(cors());

app.post("/test1", upload.single("file"), (req, res) => {
  const file = req.file;
  console.log("recv file: ", file);

  res.send({
    code: 200,
    data: "ok",
  });
});

app.listen(1901, () => {
  console.log("listen 1901");
});
```
It seems that _form.append("file", file)_ has some problem unexpected:  
![howtogetfile](https://github.com/user-attachments/assets/b33891a1-c725-429f-89a6-26f1a11b11c4)
![howtogetfile2](https://github.com/user-attachments/assets/04875a66-0caf-4c91-b723-4e4f66fa1c7c)

I also tried to save converted model file locally. And I've checked the "model.glb" file I got, it is OK：
![savefilelocally](https://github.com/user-attachments/assets/46fab8f5-d047-4eca-8b18-048b149fd2f1)

**Comment by xslasd** [comment]
I have fixed the code 'form.append("file", file, gid + ".glb")'. Please try again

**Comment by TRYOKETHEPEN** [comment]
> I have fixed the code 'form.append("file", file, gid + ".glb")'. Please try again

Thanks! The problem is resolved
